-- MySQL  generated by MySQL Workbench
-- Fri Jun 15 02:07:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema always
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema always
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `always` DEFAULT CHARACTER SET utf8 ;
USE `always` ;

-- -----------------------------------------------------
-- Table `always`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `always`.`Funcionario` (
  `idFuncionario` INT NOT NULL auto_increment,
  `nomeFuncionario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `regra` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
	`isRemovido` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `always`.`Orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `always`.`Orcamento` (
  `idOrcamento` INT NOT NULL auto_increment,
  `Status` VARCHAR(20) NOT NULL,
  `detalhamentoStd` VARCHAR(80) NOT NULL,
  `detalhamentoPrm` VARCHAR(80) NOT NULL,
  `emailFuncionario` VARCHAR(45) NOT NULL,
  `emailCliente1` VARCHAR(45) NOT NULL,
  `emailCliente2` VARCHAR(45) NOT NULL,
    `valorPremium` double not null,
  `valorStandard` double not null,
  PRIMARY KEY (`idOrcamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `always`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `always`.`Pedido` (
  `idPedido` INT NOT NULL auto_increment,
  `statusOrcamento` VARCHAR(20) NOT NULL,
  `Orcamento_idOrcamento` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Orcamento_idOrcamento`),
  INDEX `fk_Pedido_Orcamento1_idx` (`Orcamento_idOrcamento` ASC),
  CONSTRAINT `fk_Pedido_Orcamento1`
    FOREIGN KEY (`Orcamento_idOrcamento`)
    REFERENCES `always`.`Orcamento` (`idOrcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `always`.`Orcamento_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `always`.`Orcamento_Funcionario` (
  `Orcamento_idOrcamento` INT NOT NULL auto_increment,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`Orcamento_idOrcamento`, `Funcionario_idFuncionario`),
  INDEX `fk_Orcamento_has_Funcionario_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  INDEX `fk_Orcamento_has_Funcionario_Orcamento1_idx` (`Orcamento_idOrcamento` ASC),
  CONSTRAINT `fk_Orcamento_has_Funcionario_Orcamento1`
    FOREIGN KEY (`Orcamento_idOrcamento`)
    REFERENCES `always`.`Orcamento` (`idOrcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_has_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `always`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Funcionario(idFuncionario, nomeFuncionario, email, regra, senha) values
(1,'Admin', 'admin@admin.com', ' ', 'nimda'),
(808080,'Ailton dos santos', 'ailtonSantos@gmail.com', ' ', 'b423973681b571359fc30dc04d0bbf85'),
(140455,'Ronald miranda', 'ronaldPow@gmail.com', '','6fb457cd867d3f261522f118c9a4eb45'),
(402306,'Maria Loquenta', 'mariaLoq@gmail.com', '','4b6df872d5790c5f7d7b69ccf044956c'),
(787888,'Gabriel Novaes ', 'gab.nov@hotmail.com', ' ', '4d319d6e5284611afca8927396ca55bd'),
(103389,'Thaisa moreira', 'thaisa.moreira@gmail.com', ' ', '357474dd5b7d9c344508afd0f53fb7b2');

INSERT INTO Orcamento(`Status`, `detalhamentoStd`, `detalhamentoPrm`, `emailFuncionario`, `emailCliente1`, `emailCliente2`,`valorPremium`,`valorStandard`) values
('Pendente','Dados do orçamento Standard','Dados do orçamento Premium','ronaldPow@gmail.com','tadeu.rocha@gmail.com','mirian.goncalves@gmail.com',50.000, 42.000),
('Efetivado','O padrão está de acordo com o o convecional','Com o premium há cotagem de preços mais adequadas ao seu bolso','ronaldPow@gmail.com','wagner.mendoca@gmail.com','mara.deg@gmail.com',50.000, 42.000),
('Efetivado','O padrão está incluso com o tradicional do pacote básico somente','Além de incluir o básico há o premium por pacote modular','mariaLoq@gmail.com','manoelson.silva@gmail.com','mirian.goncalves@gmail.com',50.000, 42.000);

INSERT INTO Pedido(idPedido, statusOrcamento, Orcamento_idOrcamento) values
(1212,'Rejeitado',1),
(1111,'Rejeitado',2),
(4545,'Aprovado',3);

INSERT INTO Orcamento_Funcionario(Orcamento_idOrcamento, Funcionario_idFuncionario) values
(1, 140455),
(2, 140455),
(3, 140455);
