-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 16:19:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(45) NOT NULL,
  `datanasc` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convidado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Convidado` (
  `idPar` INT NOT NULL AUTO_INCREMENT,
  `Convidado1` VARCHAR(45) NOT NULL,
  `Convidado2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `uf` CHAR(2) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(100) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`, `Estado_idEstado`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(30) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `logradouro` CHAR(3) NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `Cidade_idCidade`),
  INDEX `fk_Endereco_Cidade_idx` (`Cidade_idCidade` ASC),
  CONSTRAINT `fk_Endereco_Cidade`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` VARCHAR(5) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `Convidado_idPar` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Endereco_Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `Convidado_idPar`),
  INDEX `fk_Evento_Convidado1_idx` (`Convidado_idPar` ASC),
  INDEX `fk_Evento_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  INDEX `fk_Evento_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Cidade_idCidade` ASC),
  CONSTRAINT `fk_Evento_Convidado1`
    FOREIGN KEY (`Convidado_idPar`)
    REFERENCES `mydb`.`Convidado` (`idPar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Endereco` (`idEndereco` , `Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encontro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encontro` (
  `idEncontro` INT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(45) NOT NULL,
  `data` INT NOT NULL,
  `horario` VARCHAR(5) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Endereco_Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idEncontro`, `Endereco_idEndereco`, `Endereco_Cidade_idCidade`),
  INDEX `fk_Encontro_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Cidade_idCidade` ASC),
  CONSTRAINT `fk_Encontro_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Endereco` (`idEndereco` , `Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtividade` (
  `idCliente1` INT NOT NULL,
  `idCliente2` INT NOT NULL,
  `data` DATE NOT NULL,
  `isOrcamentoAceito` TINYINT NOT NULL,
  PRIMARY KEY (`idCliente1`, `idCliente2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(13) NOT NULL,
  `datanasc` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `escolaridade` VARCHAR(20) NOT NULL,
  `dataCad` DATE NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Endereco_Cidade_idCidade` INT NOT NULL,
  `Produtividade_idCliente1` INT NOT NULL,
  `Produtividade_idCliente2` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Endereco_idEndereco`, `Endereco_Cidade_idCidade`),
  INDEX `fk_Cliente_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Cidade_idCidade` ASC),
  INDEX `fk_Cliente_Produtividade1_idx` (`Produtividade_idCliente1` ASC, `Produtividade_idCliente2` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Endereco` (`idEndereco` , `Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Produtividade1`
    FOREIGN KEY (`Produtividade_idCliente1` , `Produtividade_idCliente2`)
    REFERENCES `mydb`.`Produtividade` (`idCliente1` , `idCliente2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orcamento` (
  `idOrcamento` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `detalhamentoStd` VARCHAR(80) NOT NULL,
  `detalhamentoPrm` VARCHAR(80) NOT NULL,
  `valorStd` DOUBLE NOT NULL,
  `valorPrm` DOUBLE NOT NULL,
  `emailFuncionario` VARCHAR(45) NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  `idUltimoFuncionario` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Endereco_idEndereco` INT NOT NULL,
  `Cliente_Endereco_Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idOrcamento`),
  INDEX `fk_Orcamento_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Endereco_idEndereco` ASC, `Cliente_Endereco_Cidade_idCidade` ASC),
  CONSTRAINT `fk_Orcamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Endereco_idEndereco` , `Cliente_Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atributo` (
  `corDeCabelo` VARCHAR(20) NOT NULL,
  `codDePele` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(9) NOT NULL,
  `descricao` VARCHAR(80) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`),
  CONSTRAINT `fk_Atributo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encontro_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encontro_Cliente` (
  `Encontro_idEncontro` INT NOT NULL,
  `Encontro_Endereco_idEndereco` INT NOT NULL,
  `Encontro_Endereco_Cidade_idCidade` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Endereco_idEndereco` INT NOT NULL,
  `Cliente_Endereco_Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`Encontro_idEncontro`, `Encontro_Endereco_idEndereco`, `Encontro_Endereco_Cidade_idCidade`, `Cliente_idCliente`, `Cliente_Endereco_idEndereco`, `Cliente_Endereco_Cidade_idCidade`),
  INDEX `fk_Encontro_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Endereco_idEndereco` ASC, `Cliente_Endereco_Cidade_idCidade` ASC),
  INDEX `fk_Encontro_has_Cliente_Encontro1_idx` (`Encontro_idEncontro` ASC, `Encontro_Endereco_idEndereco` ASC, `Encontro_Endereco_Cidade_idCidade` ASC),
  CONSTRAINT `fk_Encontro_has_Cliente_Encontro1`
    FOREIGN KEY (`Encontro_idEncontro` , `Encontro_Endereco_idEndereco` , `Encontro_Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Encontro` (`idEncontro` , `Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encontro_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Endereco_idEndereco` , `Cliente_Endereco_Cidade_idCidade`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Endereco_idEndereco` , `Endereco_Cidade_idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
